// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAty-xvvx2tQHGwlnfWlx9ckYL0WKhyE-M',
    appId: '1:811650161654:web:b5b967fe77ee1ec90345d7',
    messagingSenderId: '811650161654',
    projectId: 'proj01-feba2',
    authDomain: 'proj01-feba2.firebaseapp.com',
    storageBucket: 'proj01-feba2.appspot.com',
    measurementId: 'G-CBFQ34M3EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxNCqxKYHxnojzFIcjy5SR0zC4ytNCFns',
    appId: '1:811650161654:android:c6bf4aa20b661ae40345d7',
    messagingSenderId: '811650161654',
    projectId: 'proj01-feba2',
    storageBucket: 'proj01-feba2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAStVJHLUdlv30TJP2pZ68uz-kRA0ZDr00',
    appId: '1:811650161654:ios:14c2886d79694f2c0345d7',
    messagingSenderId: '811650161654',
    projectId: 'proj01-feba2',
    storageBucket: 'proj01-feba2.appspot.com',
    iosBundleId: 'com.example.approver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAStVJHLUdlv30TJP2pZ68uz-kRA0ZDr00',
    appId: '1:811650161654:ios:14c2886d79694f2c0345d7',
    messagingSenderId: '811650161654',
    projectId: 'proj01-feba2',
    storageBucket: 'proj01-feba2.appspot.com',
    iosBundleId: 'com.example.approver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAty-xvvx2tQHGwlnfWlx9ckYL0WKhyE-M',
    appId: '1:811650161654:web:a7fcd4b583cc63120345d7',
    messagingSenderId: '811650161654',
    projectId: 'proj01-feba2',
    authDomain: 'proj01-feba2.firebaseapp.com',
    storageBucket: 'proj01-feba2.appspot.com',
    measurementId: 'G-Y0964YLWPN',
  );
}
